
create extension if not exists pgcrypto;

create type public.user_role as enum ('player','commissioner');
create type public.game_status as enum ('scheduled','live','final');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role public.user_role not null default 'player',
  created_at timestamptz not null default now()
);

create table public.weeks (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_number integer not null,
  deadline timestamptz not null,
  status text not null default 'open' check (status in ('draft','open','locked','complete')),
  tiebreaker_description text default 'Total points in the final game',
  tiebreaker_value integer,
  created_at timestamptz not null default now(),
  unique(season, week_number)
);

create table public.games (
  id uuid primary key default gen_random_uuid(),
  week_id bigint not null references public.weeks(id) on delete cascade,
  external_id text,
  kickoff timestamptz not null,
  away_team text not null,
  home_team text not null,
  spread numeric(4,1),
  spread_locked boolean not null default false,
  spread_source text,
  spread_locked_at timestamptz,
  status public.game_status not null default 'scheduled',
  away_score integer,
  home_score integer,
  created_at timestamptz not null default now(),
  unique(week_id, external_id)
);

create table public.picks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_id bigint not null references public.weeks(id) on delete cascade,
  game_id uuid not null references public.games(id) on delete cascade,
  winner_team text not null,
  confidence integer not null check (confidence between 1 and 4),
  spread_team text,
  submitted_at timestamptz not null default now(),
  unique(user_id, week_id, game_id)
);

create table public.week_scores (
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_id bigint not null references public.weeks(id) on delete cascade,
  winner_points integer not null default 0,
  spread_points integer not null default 0,
  tiebreaker_error integer,
  total_points integer generated always as (winner_points + spread_points) stored,
  primary key(user_id, week_id)
);

create or replace function public.is_commissioner()
returns boolean language sql security definer stable as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'commissioner');
$$;

alter table public.profiles enable row level security;
alter table public.weeks enable row level security;
alter table public.games enable row level security;
alter table public.picks enable row level security;
alter table public.week_scores enable row level security;

create policy "profiles readable" on public.profiles for select to authenticated using (true);
create policy "own profile update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "weeks readable" on public.weeks for select to authenticated using (true);
create policy "games readable" on public.games for select to authenticated using (true);
create policy "scores readable" on public.week_scores for select to authenticated using (true);
create policy "picks readable only after kickoff or by owner" on public.picks for select to authenticated
using (
  user_id = auth.uid()
  or public.is_commissioner()
  or exists (
    select 1 from public.games g
    where g.id = game_id and now() >= g.kickoff
  )
);
create policy "own picks insert" on public.picks for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.weeks w
    where w.id = week_id and w.status = 'open' and now() < w.deadline
  )
);
create policy "own picks update" on public.picks for update to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.weeks w
    where w.id = week_id and w.status = 'open' and now() < w.deadline
  )
);

create policy "commissioner profiles" on public.profiles for all to authenticated using (public.is_commissioner());
create policy "commissioner weeks" on public.weeks for all to authenticated using (public.is_commissioner()) with check (public.is_commissioner());
create policy "commissioner games" on public.games for all to authenticated using (public.is_commissioner()) with check (public.is_commissioner());

create or replace function public.prevent_locked_spread_change()
returns trigger language plpgsql as $$
begin
  if old.spread_locked and (
    new.spread is distinct from old.spread
    or new.spread_source is distinct from old.spread_source
  ) then
    raise exception 'Spread is locked and cannot be changed';
  end if;
  return new;
end $$;

create trigger trg_prevent_locked_spread
before update on public.games
for each row execute function public.prevent_locked_spread_change();

create policy "commissioner scores" on public.week_scores for all to authenticated using (public.is_commissioner()) with check (public.is_commissioner());

-- After creating your first account, promote it:
-- update public.profiles set role='commissioner' where id='YOUR-AUTH-USER-UUID';


-- A safe read-only view for the leaderboard/reveal layer.
-- Picks are not exposed to other players until that individual game's kickoff.
create or replace view public.revealed_picks as
select p.id, p.user_id, p.week_id, p.game_id, p.winner_team, p.confidence, p.spread_team
from public.picks p
join public.games g on g.id=p.game_id
where now() >= g.kickoff;

grant select on public.revealed_picks to authenticated;

-- Optional helper: promote a user to commissioner.
-- update public.profiles set role='commissioner' where id='YOUR-AUTH-USER-UUID';
